### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.experimental' has no attribute 'numpy'

### ISSUE THREAD

**Issue by tallamjr** [tallamjr/astronet#56]
It seems that `tensorflow` `v2.3.1` no longer works for the experimental numpy api. This may have actually always been the case and `v2.4.0` was being used all along locally. Regardless, when working in `v2.3.1` environment, the following error is thrown when attempting to use the api:
```python
    def test_numpy_average():

        numpy_API = np.average(range(1, 11), weights=range(10, 0, -1))

>       tensorflow_API = tf.experimental.numpy.average(range(1, 11), weights=range(10, 0, -1))
E       AttributeError: module 'tensorflow._api.v2.experimental' has no attribute 'numpy'

numpy_API  = 4.0

astronet/t2/tests/int/test_numpy_api.py:9: AttributeError
================================================= slowest durations ==================================================

(3 durations < 0.005s hidden.  Use -vv to show these durations.)
============================================== short test summary info ===============================================
FAILED astronet/t2/tests/int/test_numpy_api.py::test_numpy_average - AttributeError: module 'tensorflow._api.v2.exp...
================================================= 1 failed in 4.65s ==================================================

```
This test has been tried on `v2.4.0` and it passes, 
```python
Successfully installed tensorflow-2.4.0 tensorflow-estimator-2.4.0
(astronet) 13:47:29 ✔ ~/github/tallamjr/origin/astronet (issues/53/load-datasets) :: pytest astronet/t2/tests/int/test_numpy_api.py
================================================ test session starts =================================================
platform darwin -- Python 3.7.8, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /usr/local/anaconda3/envs/astronet/bin/python
cachedir: .pytest_cache
rootdir: /Users/tallamjr/github/tallamjr/origin/astronet, configfile: pytest.ini
plugins: nbval-0.9.6, cov-2.10.1, subtests-0.3.2
collected 1 item

astronet/t2/tests/int/test_numpy_api.py::test_numpy_average
        astronet/t2/tests/int/test_numpy_api.py::test_numpy_averagePASSED

================================================= slowest durations ==================================================

(3 durations < 0.005s hidden.  Use -vv to show these durations.)
================================================= 1 passed in 14.92s =================================================

```

so a solution is to upgrade the `requirements.txt` to `v2.4.0` **however**, when one does this on Hypatia, another kind of error is thrown, described here https://github.com/tensorflow/tensorflow/issues/45744 .

As of this https://github.com/tensorflow/tensorflow/issues/45744#issuecomment-754981206 there seems to be a fix in the pipeline, so on Hypatia, the plan is the revert back to `v2.3.1` until the `Illegal instruction` error is fixed and then bump to `v2.4.0` for tensorflow. The knockon effect is that no **PLAsTiCC** analysis can be run until then
